name: Build and Push Docker Image

on:
  push:
    branches:
      - main



jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Java environment
      uses: actions/setup-java@v2
      with:
        java-version: '11'

    - name: Build with Maven
      run: mvn clean package docker:build

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: "jithesh1906"
        password: "Jithesh88."

    - name: Push Docker image to Docker Hub
      run: docker push your-dockerhub-username/your-docker-image-name:latest
